apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-web
  template:
    metadata:
      labels:
        app: mi-web
    spec:
      containers:
      - name: mi-web-container
        image: mi-web-uoc:latest
        ports:
        - containerPort: 8081 # <--- CAMBIADO para no chocar con Jenkins
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "200m"
            memory: "64Mi"
