apiVersion: v1
kind: Service
metadata:
  name: mi-web-service
spec:
  type: NodePort
  selector:
    app: mi-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30081
